# Requirements covered by the Copilot AISDLC solution
covered_requirements:
  - REQ-F-PLUGIN-001
  - REQ-F-PLUGIN-002
  - REQ-F-PLUGIN-003
  - REQ-F-PLUGIN-004
  - REQ-F-CMD-001
  - REQ-F-CMD-002
  - REQ-F-CMD-003
  - REQ-F-WORKSPACE-001
  - REQ-F-WORKSPACE-002
  - REQ-F-WORKSPACE-003
  - REQ-F-UPDATE-001
  - REQ-F-TESTING-001
  - REQ-F-TESTING-002
  - REQ-NFR-TRACE-001
  - REQ-NFR-TRACE-002
  - REQ-NFR-CONTEXT-001
  - REQ-NFR-FEDERATE-001
  - REQ-NFR-COVERAGE-001
  - REQ-NFR-REFINE-001
